### ISSUE TITLE
Spark Monitoring outside nlesc

### ISSUE THREAD

**Issue by c-martinez** [nlesc-sherlock/sherlock-demo-site#3]
[Spark monitoring Environment page](http://sherlock.esciencecenter.nl:8080/) does not seem to work outside the escience center.

**Comment by sverhoeven** [comment]
Correct, this is by design, a whitelist of ip ranges is used.

**Comment by c-martinez** [comment]
Ah! I guess it is fine then. It means we cannot demo things outside nlesc, but if we were planning on doing so, we could add more addresses to the white list.
